/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.net.*;
import java.io.*;


/**
 * @author rocco
 */
public class GestoreServer extends javax.swing.JFrame {


    /**
     * Creates new form GestoreServer
     */
    public GestoreServer() {
        initComponents();
    }

    /**
     * @param s
     * @throws Exception
     */
    public void send(String s, String ip, int porta) throws Exception {
        byte[] buffer;
        DatagramPacket datagram;
        try {
            this.socket = new DatagramSocket();
            this.socket.setSoTimeout(1000);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // indirizzo IP del destinatario del datagram
        InetAddress address = InetAddress.getByName(ip);
        // verifica chiusura socket
        if (socket.isClosed()) {
            throw new IOException();
        }
        buffer = s.getBytes("UTF-8");
        datagram = new DatagramPacket(buffer, buffer.length, address, porta);
        socket.send(datagram); // trasmissione datagram di richiesta
        socket.close();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        IpTextField = new javax.swing.JTextField();
        portaTextField = new javax.swing.JTextField();
        StopBtn = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        inviaBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Avvia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IpTextField.setText("127.0.0.1");

        portaTextField.setText("7777");

        StopBtn.setText("Stop");
        StopBtn.setToolTipText("");
        StopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBtnActionPerformeded(evt);
            }
        });

        stop.setText("Riavvia");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        jLabel1.setText("Ip Server");

        jLabel2.setText("Porta Sever");

        jLabel3.setText("Gestore Server UDP");

        jLabel4.setText("Inserimento stringa manuale");

        inviaBtn.setText("Invia al server UDP");
        inviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Output console ");

        outputTextArea.setEditable(false);
        outputTextArea.setColumns(20);
        outputTextArea.setLineWrap(true);
        outputTextArea.setRows(5);
        outputTextArea.setToolTipText("");
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(StopBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(stop)
                                                .addGap(58, 58, 58))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inviaBtn))
                                                .addComponent(inputTextField)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel1))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(portaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(portaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(StopBtn)
                                        .addComponent(stop))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inviaBtn)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("invio " + this.goMessage);
        this.outputTextArea.append("invio --> " + this.goMessage + "\n");
        try {
            this.send(this.goMessage, this.IpTextField.getText(), Integer.parseInt(this.portaTextField.getText()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            this.outputTextArea.append(ex.getMessage());

        }
    }

    private void StopBtnActionPerformeded(java.awt.event.ActionEvent evt) {
        System.out.println("invio " + this.stopMessage);
        this.outputTextArea.append("invio --> " + this.stopMessage + "\n");
        try {
            this.send(this.stopMessage, this.IpTextField.getText(), Integer.parseInt(this.portaTextField.getText()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            this.outputTextArea.append(ex.getMessage());
        }
    }

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {
        this.outputTextArea.append("invio --> " + this.resetMessage + "\n");
        try {
            this.send(this.resetMessage, this.IpTextField.getText(), Integer.parseInt(this.portaTextField.getText()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            this.outputTextArea.append(ex.getMessage());
        }
    }

    private void inviaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("invio " + this.inputTextField.getText());
        this.outputTextArea.append("invio --> " + this.inputTextField.getText() + "\n");
        try {
            this.send(this.inputTextField.getText(), this.IpTextField.getText(), Integer.parseInt(this.portaTextField.getText()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            this.outputTextArea.append(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestoreServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestoreServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestoreServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestoreServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestoreServer().setVisible(true);

            }
        });

    }


    private String resetMessage = "RESETTUTTI";
    private String goMessage = "GOTUTTI";
    private String stopMessage = "STOPTUTTI";
    private DatagramSocket socket;
    // Variables declaration - do not modify                     
    private javax.swing.JTextField IpTextField;
    private javax.swing.JButton StopBtn;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JButton inviaBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JTextField portaTextField;
    private javax.swing.JButton stop;
    // End of variables declaration                   
}